name: iconvert
description: A minimal dart image converter library supporting multiple formats (PNG, JPG, BMP, GIF, TIFF, ICO).
version: 1.0.0
repository: https://github.com/Sten435/iconvert

environment:
  sdk: ^3.0.0

dependencies:
  image: ^4.7.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
